import torch
import sys
import os

# Add model directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'model'))
from inference import ModelPredictor

def format_tokens(tokens):
    result = ""
    for t in tokens:
        if t in ['<EOL>', '</s>', '<PAD>', '<UNK>']:
            continue
            
        # Punctuation that usually attaches to the preceding word
        if t in ['.', ':', ',', ')', ']', '}']:
            result += t
        # Open brackets often attach to the preceding word (e.g. func( )
        elif t in ['(', '[', '{']:
            result += t
        else:
            # If the current result ends with alphanumeric, we need a space
            if result and (result[-1].isalnum() or result[-1] in ["'", '"']):
                result += " " + t
            else:
                # E.g. after '(' or ' ' or '[' we don't necessarily need a space before alphanumeric
                # Wait, operators like '=' should have spaces around them.
                if t in ['=', '==', '!=', '+=', '-=', '>=', '<=', '+', '-', '*', '/']:
                    result += " " + t + " "
                else:
                    if result and result[-1] not in [' ', '(', '[', '.']:
                        result += " " + t
                    else:
                        result += t
                        
    # Clean up any double spaces generated by operators
    result = result.replace("  ", " ")
    return result.strip()


def test_prompts():
    predictor = ModelPredictor()
    
    # We will temporarily override the predict_line method to stop at <EOL>
    # and return both raw tokens and formatted text
    
    prompts = [
        "def calculate_sum",
        "import",
        "for i in range",
        "class MyModel",
        "x ="
    ]
    
    for prompt in prompts:
        print(f"\n--- PROMPT: '{prompt}' ---")
        
        # Tokenize prompt using the predictor's vocab
        import re
        tokens = re.findall(r'[a-zA-Z_]\w*|\d+(?:\.\d+)?|==|!=|<=|>=|\/\/|\*\*|[-+*/=<>!&|~^%]|[\(\)\[\]\{\}\.,:;@\n]', prompt)
        
        input_ids = [predictor.token_to_id.get(token, predictor.unk_id) for token in tokens[-999:]]
        
        generated_tokens = []
        
        with torch.no_grad():
            for _ in range(15): # max 15 tokens
                input_tensor = torch.tensor([input_ids], dtype=torch.long).to(predictor.device)
                outputs, _ = predictor.model(input_tensor)
                logits = outputs[0, -1, :] 
                
                # Mask UNK
                logits[predictor.unk_id] = -float('Inf')
                
                best_token_idx = torch.argmax(logits).item()
                best_token = predictor.id_to_token.get(best_token_idx, "")
                
                if best_token in ["<EOL>", "</s>", ""]:
                    generated_tokens.append(best_token)
                    break
                    
                generated_tokens.append(best_token)
                input_ids.append(best_token_idx)
                
        formatted = format_tokens(generated_tokens)
        print(f"RAW TOKENS: {generated_tokens}")
        print(f"FORMATTED:  {formatted}")

if __name__ == '__main__':
    test_prompts()
